config/routes.rb
Rails.application.routes.draw do
  # mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "facts#index"
  get "/pages/about" => "pages#about", as: :about
  resources :facts do
    resources :sources
  end

  resources :sources do
  	member do
  		post 'upvote'
  	end
  end

    resources :sources do
    member do
      post 'downvote'
    end
  end
  
  resources :upvote

  resources :users

  get "/log-in" => "sessions#new", as: :login
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
end

app/models/fact.rb
class Fact < ApplicationRecord
  belongs_to :user
	has_many :sources


  def self.search(search)
  	if search

  		if self.where("title like ?", "%#{search}%").count ==0
  			self.all
  		else
  			self.where("title like ?", "%#{search}%")
  		end

  	else
    	self.all
  	end

  end
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController

	before_action :find_fact, only: [:edit, :update, :show, :delete]

  # Index action to render all posts
  def index
    @facts = Fact.search(params[:search])
  end

  # New action for creating post
  def new
    if current_user != nil
      @fact = Fact.new
    else
      flash[:danger] = "Sign in to create a fact"
      redirect_to facts_path
    end
  end

  # Create action saves the post into database
  def create
    @fact = Fact.new(fact_params)
    @fact.user_id = current_user.id
    if @fact.save
      flash[:notice] = "Successfully created post!"
      redirect_to fact_path(@fact)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
    if current_user == nil
      flash[:danger] = "Sign in to edit facts"
      redirect_to fact_path(@fact)
    elsif @fact.user_id != current_user.id
      flash[:danger] = "You can only update your own facts"
      redirect_to fact_path(@fact)
    end
  end

  # Update action updates the post with the new information
  def update
  	    @fact = Fact.find(params[:id])
        if @fact.update_attributes(fact_params)
          flash[:notice] = "Successfully updated post!"
          redirect_to fact_path(@fact)
        else
          flash[:alert] = "Error updating post!"
          render :edit
        end
  end

  # The show action renders the individual post after retrieving the the id
  def show
  end

  # The destroy action removes the post permanently from the database
  def destroy
    @fact = Fact.find(params[:id])
    if current_user !=nil
        if @fact.user_id == current_user.id
          if @fact.destroy
            flash[:notice] = "Successfully deleted fact!"
            redirect_to facts_path
          else
            flash[:danger] = "Error deleting fact"
            redirect_to fact_path(@fact)
          end
        else
          flash[:danger] = "You can only delete your own facts"
          redirect_to fact_path(@fact)
        end
    else
      flash[:danger] = "Sign in to delete facts"
      redirect_to fact_path(@fact)
    end

  end

  private

  def fact_params
    params.require(:fact).permit(:title, :context)
  end

  def find_fact
    @fact = Fact.find(params[:id])
  end
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/views/facts/_form.html.erb
<%= simple_form_for @fact do |f| %>
  <% if @fact.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@fact.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @fact.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :context, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/facts/edit.html.erb
<h2>Edit Fact</h2>

<%= render "facts/form" %>

app/views/facts/index.html.erb
<%= stylesheet_link_tag "facts.css" %>
<div class="pageBox">
  <div id= "titleBox">

    <div class ="titleTxt">
      Source Monkey
    </div>


    <div class="menuLine">
      <div class="menuLeft">
        <%= link_to "Login",login_path %>
        <%= link_to "Log out",log_out_path %>
      </div>


    <div class = "search">
      <%= form_tag facts_path, :method => 'get' do %>

          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search Fact", :name =>nil %>

      <% end %>
    </div>
    </div>
  </div>



<% if current_user != nil %>
<p><%= current_user.email %></p>
<% end %>

<%= link_to "Create New Fact",new_fact_path %>
  <div class="container">
    <div class="factInfo">
      <% @facts.each do |fact| %>
      <div class="col-xs-12">
        <div class="text-center">
          <h2><%= fact.title %></h2>
          <h6><%= fact.created_at.strftime('%b %d, %Y') %></h6>
        </div>

        <div class="text-center">
          <%= link_to "READ MORE", fact_path(fact) %>
        </div>
        <br>
      </div>
      <% end %>
    </div>
  </div>

</div>

app/views/facts/new.html.erb
<h2>Create New Fact</h2>
<%= link_to "Home",facts_path %>
<%= render "facts/form" %>

app/views/facts/show.html.erb
  <h2 class="text-center"><%= @fact.title %></h2>
  <h5 class="text-center"><%= @fact.created_at.strftime('%b %d, %Y') %></h5>

  <div><%= raw @fact.context %></div>
  <%= link_to "edit",edit_fact_path(@fact) %>| <%= link_to "delete", fact_path(@fact), method: :delete, data: {confirm: "Are you sure you want to delete this fact?"} %> | <%= link_to "Home",facts_path %>

<%if @fact.sources.count > 0 %>
    <h2>Sources</h2>
    <%= render @fact.sources.order("created_at DESC") %>
<% end %>


<h4>Site your Source:</h4>
    <%= form_for [@fact, @fact.sources.build] do |s| %>
        <%= s.text_field :source, placeholder:"Site your source"%>
        <%=s.submit %>
    <% end %>